### ISSUE TITLE
A7800 5.0 having much slowdown and not working if selecting BGFX

### ISSUE THREAD

**Issue by Augusto7743** [7800-devtools/a7800#4]
Hello.
Thanks for creating A7800.

Ubuntu 20.04.3 Nvidia driver 470 FX6300.
Trying run A7800
Opengl 50 % emulation speed
BGFX after trying load an rom the screen not is rendered only being displayed an blank screen.

Version 4.0 run correctly, but is more slow than MAME.

Trying load Popeye run emulation speed
A7800 standard or xm expansion mode 5.0 50 %
A7800 standard or xm expansion mode 4.0 85 %
MAME 0.242 105 %

In https://github.com/7800-devtools/a7800 have information about features.
The mame driver was changed ?
Have details about performance adjustments in CPU and GPU.

I not understand if good performance is your goal.
Thus being that issue is only for reporting.

Have an nice week.

**Comment by msaarna** [comment]
Thanks for the report. The decrease in performance from 4.0 to 50 is due to the mid-line updates. Basically the previous releases wouldn't account for any graphical register changes that happen mid-line, unlike a real console. To accomplish this, we needed timer events for each pixel, rather than each scanline, which added overhead.

The enhancements listed at your link are what has been added, to this fork of the Mame a7800 driver.

**Comment by Augusto7743** [comment]
@msaarna

Thanks for your reply.

"timer events for each pixel"
That feature is only in A7800 ?

Thanks for your improvements in A7800.
Have an nice day.

**Comment by msaarna** [comment]
It's in a7800, but not the a7800 Mame driver.
In terms of other emulators, some do the equivalent for mid-line updates, and some behave like the Mame version. Depends on the emulator.

**Comment by Augusto7743** [comment]
You are saying your A7800 use MAME A7800 code plus your own emulation improvements and fixes ?

**Comment by msaarna** [comment]
Yes, correct. It's mentioned in the [READM](https://github.com/7800-devtools/a7800#readme), which is also showed at the repository page.

**Comment by Augusto7743** [comment]
Thanks very much for your improvements.
Have an nice week.
